name: istanbul_graph
description: A Flutter app to visualize Istanbul districts' neighborhood relationships.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  graphview: ^1.0.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/istanbul.svg
    - assets/istanbulMap.jpg
    - assets/ist.png
    - assets\istanbul_sticker_1.png
    - assets\istanbul_sticker_2.png
    - assets\istanbul_sticker_3.png

